version: v1
project:
  id: gitpod-staging
  environment: staging
  gcpSACredFile: /mnt/secrets/gcp-sa/service-account.json
  network: gitpod-staging
  dnsZone: gitpod-staging-com
  bucket: gitpod-staging-terraform
gitpod:
  releaseName: gitpod
metaClusters:
- name: dev-stag-meta-eu01
  region: europe-west1
- name: dev-stag-meta-us01
  region: us-west1
workspaceClusters:
- region: europe-west1
  prefix: eu
  governedBy: dev-stag-meta-eu01
  type: gke
  valuesFiles:
  - values.staging.yaml
  - values.ws-cluster.yaml
- region: us-west1
  prefix: us
  governedBy: dev-stag-meta-us01
  type: gke
  valuesFiles:
  - values.staging.yaml
  - values.ws-cluster.yaml
